# Generated by Django 5.2.4 on 2025-07-27 14:09

import django_resized.forms
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Event",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                (
                    "event_type",
                    models.CharField(
                        choices=[
                            ("workshop", "Workshop"),
                            ("seminar", "Seminar"),
                            ("conference", "Conference"),
                            ("webinar", "Webinar"),
                        ],
                        max_length=20,
                    ),
                ),
                ("date", models.DateTimeField()),
                ("location", models.CharField(max_length=100)),
                ("description", models.TextField()),
                ("is_upcoming", models.BooleanField(default=True)),
            ],
            options={
                "ordering": ["-date"],
            },
        ),
        migrations.CreateModel(
            name="News",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("date", models.DateField()),
                ("summary", models.TextField()),
                ("is_featured", models.BooleanField(default=False)),
            ],
            options={
                "verbose_name_plural": "News",
                "ordering": ["-date"],
            },
        ),
        migrations.CreateModel(
            name="Opportunity",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=100)),
                (
                    "position_type",
                    models.CharField(
                        choices=[
                            ("phd", "PhD Position"),
                            ("postdoc", "Post-doctoral Position"),
                            ("intern", "Internship"),
                            ("ra", "Research Assistant"),
                        ],
                        max_length=20,
                    ),
                ),
                ("description", models.TextField()),
                ("requirements", models.TextField()),
                ("is_active", models.BooleanField(default=True)),
            ],
            options={
                "verbose_name_plural": "Opportunities",
                "ordering": ["-is_active", "position_type"],
            },
        ),
        migrations.CreateModel(
            name="Publication",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=300)),
                ("authors", models.CharField(max_length=200)),
                (
                    "pub_type",
                    models.CharField(
                        choices=[
                            ("journal", "Journal Article"),
                            ("conference", "Conference Paper"),
                            ("book", "Book Chapter"),
                            ("report", "Report"),
                        ],
                        max_length=20,
                    ),
                ),
                ("journal_conference", models.CharField(max_length=200)),
                ("year", models.PositiveIntegerField()),
                ("abstract", models.TextField()),
                ("link", models.URLField()),
            ],
            options={
                "ordering": ["-year"],
            },
        ),
        migrations.CreateModel(
            name="ResearchArea",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=100)),
                ("description", models.TextField()),
                ("icon_class", models.CharField(blank=True, max_length=50)),
            ],
            options={
                "verbose_name_plural": "Research Areas",
                "ordering": ["title"],
            },
        ),
        migrations.CreateModel(
            name="TeamMember",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("designation", models.CharField(max_length=100)),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("director", "Director"),
                            ("phd", "PhD Scholar"),
                            ("postdoc", "Post-doctoral Researcher"),
                            ("associate", "Research Associate"),
                        ],
                        max_length=20,
                    ),
                ),
                ("bio", models.TextField()),
                (
                    "photo",
                    django_resized.forms.ResizedImageField(
                        blank=True,
                        crop=["middle", "center"],
                        force_format=None,
                        keep_meta=True,
                        null=True,
                        quality=-1,
                        scale=None,
                        size=[300, 300],
                        upload_to="team/",
                    ),
                ),
                ("research_interests", models.TextField()),
                ("profile_link", models.URLField(blank=True)),
            ],
            options={
                "ordering": ["category", "name"],
            },
        ),
    ]
