# Generated by Django 5.2.4 on 2025-08-05 09:54

import django.utils.timezone
import django_resized.forms
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("lab", "0002_contact"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="opportunity",
            options={
                "ordering": ["-is_active", "deadline", "position_type"],
                "verbose_name_plural": "Opportunities",
            },
        ),
        migrations.RenameField(
            model_name="teammember",
            old_name="profile_link",
            new_name="google_scholar_link",
        ),
        migrations.RemoveField(
            model_name="event",
            name="is_upcoming",
        ),
        migrations.AddField(
            model_name="event",
            name="registration_link",
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="news",
            name="featured_image",
            field=django_resized.forms.ResizedImageField(
                blank=True,
                crop=["middle", "center"],
                force_format=None,
                keep_meta=True,
                null=True,
                quality=-1,
                scale=None,
                size=[800, 450],
                upload_to="news/",
            ),
        ),
        migrations.AddField(
            model_name="news",
            name="full_story_content",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="news",
            name="slug",
            field=models.SlugField(blank=True, max_length=255, unique=True),
        ),
        migrations.AddField(
            model_name="opportunity",
            name="application_link",
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="opportunity",
            name="deadline",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="teammember",
            name="linkedin_link",
            field=models.URLField(blank=True),
        ),
        migrations.AlterField(
            model_name="news",
            name="date",
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name="researcharea",
            name="icon_class",
            field=models.CharField(
                blank=True,
                help_text="e.g., fas fa-bolt for Font Awesome icon",
                max_length=50,
            ),
        ),
    ]
