# Generated by Django 5.2.4 on 2025-08-06 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("lab", "0003_alter_opportunity_options_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="event",
            name="slug",
            field=models.SlugField(blank=True, max_length=200, unique=True),
        ),
    ]
