# Generated by Django 5.2.4 on 2026-02-26 07:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lab', '0004_event_slug'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='teammember',
            options={'ordering': ['category', 'display_order', 'name']},
        ),
        migrations.AddField(
            model_name='teammember',
            name='display_order',
            field=models.PositiveIntegerField(default=999, help_text='Lower number shows first (e.g., 1,2,3...).'),
        ),
    ]
