# Generated by Django 5.2.4 on 2026-02-26 07:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lab', '0005_alter_teammember_options_teammember_display_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teammember',
            name='category',
            field=models.CharField(choices=[('director', 'Director'), ('1phd', 'PhD Scholar'), ('2postdoc', 'Post-doctoral Researcher'), ('3associate', 'Research Associate')], max_length=20),
        ),
    ]
